### ISSUE TITLE
Getting total supporters count is hard

### ISSUE THREAD

**Issue by danhenderson** [blackbaud-services/supporticon#16]
`pages-totals` uses `api/v2/pages`, which accepts `start_created_at` and `end_created_at`, which is required for many supporter counts. But it doesn't support filtering that total by group values.

And of course the `api/v2/search/pages` endpoint allows group values, but doesn't support filtering by date.

Worth cross checking react-widgets and seeing how it handles it I guess, and coming up with a decent solution.

**Comment by bradparker** [comment]
Total supporters filtered by date?

Do you want total count and grouped totals in one request?

**Comment by danhenderson** [comment]
Yeah, so for example, a certain campaign might only want a count of how many supporters have created pages this year.

As for data, all we want in these cases is a total count of supporters, which traditionally is done by looking at the pagination data returned by the above endpoints i.e. `meta.pagination.count`.

My issue is just that `api/v2/pages` allows me to query using start/end dates, while `api/v2/search/pages` allows me to query using group values, but not vice-versa, so it's just hard to find a solution to add here in supporticon that abstracts all that away and works for either.
