### ISSUE TITLE
Do not default country to 'au'

### ISSUE THREAD

**Issue by sourcier** [blackbaud-services/supporticon#172]
The signup method defaults the users country code value to 'au'

https://github.com/everydayhero/supporticon/blob/master/source/api/authentication/everydayhero/index.js#L41

This property should be required and not defaulted and throw an error if it is not set

If a developer forgets to set the country value, there could be a mismatch, this is the current case in Run26:

https://github.com/blackbaud-services/diabetes-uk-run-26/blob/master/source/store/session/user/index.js#L19

**Comment by danhenderson** [comment]
As we spoke about, as a first step, just pass in `gb` in Run26 (and other UK projects going forward).

And then we can have a discussion whether we want to make this param required moving forward. It makes sense not to hardcode it to Australia, but it's obviously a breaking change, so we just need to weigh up the trade off.

**Comment by rowanhogan** [comment]
🇦🇺🇦🇺🇦🇺
